### ISSUE TITLE
How do I adjust the retention duration without using Carbon-Relay-NG

### ISSUE THREAD

**Issue by OscarVanL** [grafana/cloud-graphite-scripts#11]
Hi,

I'm using a python script to POST data to a Grafana-hosted Graphite store as in these examples.

I would like to adjust the retention duration to keep data for longer. However, the documentation says to do this using Carbon-Relay-NG by creating `/etc/carbon-relay-ng/storage-schemas.conf`.

Is there any way to adjust Graphite's retention duration without using Carbon-Relay-NG?

Thanks.

**Comment by Dieterbe** [comment]
> However, the documentation says to do this using Carbon-Relay-NG by creating /etc/carbon-relay-ng/storage-schemas.conf

that's incorrect. can you point us to the documentation that says this? the storage-schemas.conf file is only used to assign intervals, not to control retention.

to adjust retention you should reach out to the support team.

**Comment by OscarVanL** [comment]
Hi, perhaps I misunderstood this then. I was reading the page at `https://grafana.com/orgs/<org-name>/hosted-metrics/<id>`

![image](https://user-images.githubusercontent.com/7999692/103357498-41478000-4aab-11eb-8a25-cd0c7f8ffef4.png)

I presumed this meant that there would be data retention of 1 day for any data sent using this config.

The reason I asked this question is I'm trying to 'replay' some 1-month-old IoT data I have stored on my local machine. I'm setting the time fields appropriately:

            {
                "name": "sensor.humidity",
                "value": payload.humidity,
                "interval": interval,
                "unit": "%",
                "time": int(payload.time.timestamp()),
                "mtype": "gauge",
            }

In the earliest case, the `time` field correlates to December 1st 2020.

I make the POSTs to Graphite, I get a 200 success response, but I can't see any of my old 'replayed' data appearing in Grafana's dashboard panels, or in the 'Explore' page, even if I set the relative time range to 30/90 days.

I know these POSTs are properly formatted, as if I use the same code for "live" data from my IoT device, it appears fine.
![image](https://user-images.githubusercontent.com/7999692/103358008-7accbb00-4aac-11eb-9353-60f34579d30b.png)


Is replaying data with old timestamps a supported feature? Am I doing it in the correct way?

**Comment by Dieterbe** [comment]
i see now how that page is misleading. I'll get a clarification pushed.
I believe retention should be 2 years. But one caveat is that once data is submitted for a given metric, you cannot send older data using the same metricname you've sent later data for. If you want to do that you need to use a different name. this is a limitation we're working on removing.

**Comment by OscarVanL** [comment]
Thanks for the clarification. The limitation you mentioned would explain the behaviour I was encountering.
